DROP DATABASE carometro;
GO

CREATE DATABASE carometro
GO 

USE carometro 
GO

CREATE TABLE TIPOUSUARIO (
  idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
  nomeTipoUsuario VARCHAR(30) NOT NULL
);
GO

CREATE TABLE USUARIO (
  idUsuario INT PRIMARY KEY IDENTITY,
  idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
  nomeUsuario VARCHAR(90) UNIQUE NOT NULL,
  email VARCHAR(256) UNIQUE NOT NULL,
  senha VARCHAR(72) NOT NULL
);
GO

CREATE TABLE TURMA (
  idTurma TINYINT PRIMARY KEY IDENTITY,
  descricaoTurma VARCHAR(30) NOT NULL
);
GO

CREATE TABLE ALUNO (
  idAluno INT PRIMARY KEY IDENTITY,
  idTurma TINYINT FOREIGN KEY REFERENCES TURMA(idTurma),
  nomeAluno VARCHAR(90) NOT NULL,
  RM VARCHAR(10) NOT NULL,
  dataNascimento DATE NOT NULL,
  CPF CHAR(14) NOT NULL,
  telefoneCel VARCHAR(11) NOT NULL,
  telefoneFixo VARCHAR(10) NOT NULL,
  emailAluno VARCHAR(256) NOT NULL,
  emailResponsavel VARCHAR(256) NOT NULL,
  URLimg VARCHAR(256) NOT NULL
);
GO

CREATE TABLE COMENTARIO (
  idComentario INT PRIMARY KEY IDENTITY,
  idAluno INT FOREIGN KEY REFERENCES ALUNO(idAluno),
  idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
  descricao VARCHAR(500) NOT NULL
);
GO
select * from USUARIO